#+title: 如何读一本书-笔记
#+author: mxCynic
#+date: 2024-01-12

* 第一章 阅读的活力与艺术
** 粗略的给阅读艺术下的定义:
这是一个凭借着头脑运作,除了玩味读物中的一些字句之外,不假任何外助,以一己之力来提升自我的过程
你的头脑从粗浅的了解推进到深入的理解.而会产生这种结果的运作技巧,就是由许多不同活动所组合成的阅读的艺术.
** 阅读就是学习:
阅读分为指导性的学习,以及自我发现型学习两种形式
如果阅读只是运用了自身的记忆力,那么除了那些讯息之外一无所获.并没有受到启发.  

蒙田说:"初学者的无知在于未学,而学者的无知在于学后"
这强调了阅读的质量胜过数量的重要性  

*思考*是自我发现型学习与指导性学习的共性
"老师"的出席与缺席是这两种学习的主要区别
* 第二章 阅读的层次
   阅读被分为四个层次，它们是渐进的，高层次包含低层次。
** 第一层---基础阅读
单纯指能识字,已经摆脱文盲的程度.能开始做阅读训练.
如果可以克服这个层次的困难,通常能让我们读的更快一些
** 第二层---检视阅读
略读或预读,在一定的时间内,抓住一本书的重点,检视阅读是系统化略读的一门艺术
在这个层次的目标是,从表面上观察这本书,学习到书的表面所教的一切
** 第三层次---分析阅读
花更多的时间的一种专注的活动,是咀嚼与消化一本书
** 第四层次---主题阅读
阅读大量的书,而不是一本书.是最主动的,也是最花费力气的一种阅读
* 第三章 阅读的第一个层次---基础阅读
  主要是在小学教育中训练
* 第四章 阅读的第二个层次---检视阅读
  检视阅读一共有两种,这是一体两面的事.
** 检视阅读一:有系统的略读或粗读
   略读的习惯不应花费过多的时间,我们重点关注:
   1. 书名和序
   2. 研究目录
   3. 检阅索引
   4. 阅读出版者的介绍
   5. 挑几个篇章看看(尤其是开头或结尾的摘要说明)
   6. 把书完整的翻一边,有时连续的读几页,但不要太多
** 检视阅读二:粗浅的阅读
   这时候的目标不在于弄懂书,而在于完整的把书读一遍(完整!!!).
   碰到不理解的先跳过,不停顿.这样才能有收获,而不是停在原地左顾右盼.
   对于后续的重复阅读也是有好处的.
* 第五章 如何做一个自我要求的作者
  阅读的目标如果是利益(不论什么方面的),就得保持清醒,要尽可能的保持主动.
** 主动阅读的核心:提出问题(这是绝不可忘的原则)
   可以尝试独自回答以下的问题(当然,不应该局限于这些问题.)
   1. 这本书的作者在讲述什么
   2. 作者着重在那些方面仔细的谈论过.
   3. 这本书书说的对吗?是完全对,还是部分对,或者是大错特错.(这个问题的答案建立在前两个问题的理解上)
   4. 这本书和自己有什么关系.我为什么要读这本书.(不应该用感兴趣来回答这个.)
** 如何让一本书真正属于你自己
   这个问题的答案是做笔记.
   笔记的目的是保持清醒、证明在思考，并记住作者的思想。
   做笔记,其实就是在表达自己和作者相同或相异的观点,这是读者对作者最高的敬意.
** 三种做笔记的方法

*** 结构笔记
    重点在于全书的架构,而不是内容和细节,在检视阅读后应该可以完成.
*** 概念笔记
    重点在于记录作者的观点,以及自己的看法,这是在分析阅读的过程中慢慢补充的.
*** 辩证笔记
    在主题阅读中,就某一个主题,将多位作者和自己的观点比较,通常需要单独的来记录
** 培养阅读的习惯
   要养成习惯,除了不断的练习外,别无他法.
   艺术也是要按照规则,不断的练习的,一定的规则很重要.
   阅读的艺术也是如此.
** 由许多规则中养成一个习惯
   规则的多样化,表现出来的是养成习惯的复杂程度,而非要养成多个习惯
   熟悉规则,然后"忘记"规则,注意力也就能从这些习惯的规则转移到目标上了.
 
* 第六章 一本书的分类
** 书籍分类的重要性
   分析阅读的第一个规则就是:你一定要知道自己在读的是那一类的书,而且要愈早知道愈好,
   也就是说,应该在分析阅读前,也就是在检视阅读的阶段分辨出来.
** 从一本书的书名中你能学到什么?
   能一定的程度上帮助我们分辨出这本书的分类,但是很多时候并不能靠书名分辨出来
   重要的是形成自己的,对书籍分类的标准
** 实用性VS.理论性作品
*** 实用性:教会你做一些什么,同时也会有规劝的成分
    譬如说本书(如何阅读一本书),就是实用性的,在教我读书的同时,也在试图让我认同他的观点.

*** 理论性:试图让读者明白或了解某件事
    1. 历史就是纪事,历史学家在描述历史时,或多或少会带有自己的理解,评论或意见.
    2. 哲学与科学类似,他们都是追求一般真理,一般来说,讨论日常生活的
       是哲学类的,而超出了日常生活经验的则是科学.
* 第七章 透视一本书
  每一本书都有自己的一套框架,分析阅读的目标之一就是理清楚这一套框架.
  由此引出分析阅读的第二个规则:尝试用尽可能短的文字,语句,来描述一本书的内容.
  PS.如果你的描述使用的文字过多,只能说明你并没有将整体的内容看清楚,而只是看到了多样的内容.
  而分析阅读的第三个规则是:将书中重要的章节列举出来,说明他们如何按照顺序组成一个整体.
  在这里重要的是,理清楚他们是如何组成的一个整体,而不是简单的把他们列举出来.
** 结构与规划
   一本书的结构与规划,能叙述整本书的大意.
** 驾驭复杂的内容:为一本书拟大纲的技巧
   第二个规则与第三个规则联系紧密,但是合在一起则是复杂的规则,
   将复杂的事情拆开有助于解决问题.  
   并非所有的书都值得为其编写大纲，因为你也没有那么多时间。
   但是读完一本书,至少心中要对这本书有一个模糊的大纲.  
   大纲也不一定要十分的完美,对重要的好书,尽可能的按照规则来写即可.
   不一定要按照原书出现的章节来归纳一本书的架构,你有可能做的更好.
   原书的章节是指南,是可以参考的.但是不能依赖它.  
   只有做好第三个规则,才能做好第二个规则.
   实际上这两个(第二和第三)规则,除了可以对一整本书使用,也可以对书中某一个章节使用.
** 发现作者的意图
   分析阅读的第四个规则:找出作者要问的问题.
   这一规则和前两个规则有着前后呼应的效果.
** 分析阅读的第一个阶段
   第一个阶段就是完成以上的四个分析阅读的规则.
   但是要记住,并不是说详细的读完一遍整本书,只完成这第一个阶段.
   而是说:多个阶段同时进行,读者应该多思考,而不是局限于某一个方面去思考.
* 第八章 与作者找出共通的词义
  在自然语言中,字词或多或少的会出现歧义,
  这里的目标就是正确的理解作者想要传达给读者的东西.
  如果这点做不到，那么阅读就没有收获。
  在这个过程中,读者需要自己努力的思考.
  分析阅读第五个规则：找出重要的单字，透过他们与作者达成共识。
** 找出关键字
   这是作者希望你能注意到的字词
   从一个读者的角度来看，最重要的字也就是那些让读者头疼的字。
** 专门用语以及特殊字汇
   每一个知识领域都有独特的专门用语。
   译者这里的专门用语在或许用专有名词更好？
   读者应该有好奇心去了解那些专门用语和特殊字汇到底代表着什么，
   否则，读者和作者之间的沟通就不存在了
** 找出词义
   一定要用上下文自己已经了解的所有字句，来推敲出你所不了解的那些字词的意义
   文字和词义是本章最重要的两个东西，
   文字：是作者之间写出来的，读者直接能够观察到的。
   词义：某一段文字中，作者想要传递给读者的信息。
   自然语言都是模糊不清的。
   同一短文字可以有很多不同的词义，另一方面，不同的文字有可能代表同样的词义。
   实际上，书中的文字一般是不中要的（专业的术语很重要，比如数学的极限）读者真正需要的是找出词义
* 第九章 判断作者的主旨(propositions)
   读者只有和作者达成共识，才能明白作者的主旨是什么。
   作者的主旨如果没有得到理论的支持，就只是在抒发个人想法罢了。
** 句子与主旨
   一本书由很多很多句子构成，有疑问句，有陈述句，但只有很少的句子才会表达作者的主旨
   主旨声明的是知识或观点。
   要注意文中的一些语法，主要是注意那些连词，如果、、、那么，因此、、、这样的词语   
   分析阅读第六个规则：将一本书中最重要的句子圈出来，找出其中的主旨。
   分析阅读第七个规则：从相关文句的关联中，设法架构出一本书的基本论述。
   作者沟通的核心是他所下的肯定或者否定的判断。
   文字并不完全是传递知识的媒介，在被读者解析前，文字只是字，只有读者解析后，文字才能被转换成知识。
** 找出关键句
   找出关键句的目的是找作者的主旨。   
   关键句应该从作者和读者两方面来看：
   对于作者：关键句就是阐述作者判断的地方，有些作者会给这些句子加粗或下划线。
   对于读者：关键句就是那些不能读一遍就能理解的句子。一本书那么多句子，
   大部分都是快速读完就能和作者达成共识的。
   阅读的一本分本质就是，被困惑，而且知道自己被困惑   
** 找出主旨
   如果你能找出关键句，那么就可以尝试通过这些关键句，来提炼出句子的主旨了。
   什么是句子的主旨？就是句子在说什么。应该尝试用自己的语言来复述句子的主旨。
** 找出论述
   论述是指：一系列先后顺序的主旨，这一系列主旨表达了作者的见解。
   
   在任何一本书中都只有少部分段落有论述。

   一个好的论述可以用简短的话说出来，读者应该找出好的论述并尝试用简短的话复述。

   为了找出论述，有这样一些事儿应该注意：
   1. 首先，所有的论述都包含了一些声明，有结论，也有理由。先看到结论就去找理由，先发现理由就去找结论。
   2. 其次，有归纳法和演绎法两种论述，用实验来证实主张（归纳法）或者用推论来证实主张（演绎法）。
   3. 找出作者的假设、能证实的或有根据的、不需要证实的自明之理。实际上就是找出论述的开端。
** 找出解答
   在找出解答前，读者应该找出问题，作者提出的或者自己被困惑的。
   分析阅读的第八个规则：找出作者的解答。
* 公正的评断一本书
  只有真正完成分析阅读前两个阶段了才能开始第三个阶段。  
  主动的阅读不会在已经了解到一本书在说什么就停下，而是会发表自己的意见看法，
  能说出为什么同意作者的某些看法(赞同)，以及为什么不同意作者的某些结论（批评）。
** 受教的美德
   最能学习的读者，也就是最能受批评的读者。
** 修辞的作用
   站在叙述者或者作者的角度：修辞的目的是为了说服对方。  
   站在读者的角度： 修辞的技巧是知道当别人想要说服自己时，应该如何反应。  
   分析阅读的第九个规则：在评论作者的看法前，一定要能肯定的说：我已经清楚作者想说什么了。  
   毫无理解便同意是愚蠢，还不清楚就批评是无礼。  
** 避免争强好辩的重要性
   规则十：在不同意作者观点时，应该理性的发表评论。不应无礼的辩驳或争论。  
   这个规则不应该只运用在阅读上，在任何时候都应该尽可能理性的发表评论
** 化解争议
   争议在所难免，我们不应无礼的辩驳或争论，但是也不需要躲避争论，在争论中，
   即是教导别人，也是受教的一个机会。  
   读者应该学会区分作者的观点是理论说明还是个人观点的阐述。
   如果只是作者个人的观点，则有可能被读者驳倒。  
   规则十一：理解知识与个人观点的不同，在做出任何评论之前，都要找出理论基础。

