#+title: 如何读一本书-笔记
#+author: mxCynic
#+date: 2024-01-12

* 第一章 阅读的活力与艺术
** 粗略的给阅读艺术下的定义:
这是一个凭借着头脑运作,除了玩味读物中的一些字句之外,不假任何外助,以一己之力来提升自我的过程
你的头脑从粗浅的了解推进到深入的理解.而会产生这种结果的运作技巧,就是由许多不同活动所组合成的阅读的艺术.
** 阅读就是学习:指导性的学习,以及自我发现型学习之间的差异
如果阅读只是运用了自身的记忆力,那么除了那些讯息之外一无所获.并没有受到启发.

蒙田说:"初学者的无知在于为学,而学者的无知在于学后"-
着告诉我们并不是读的越多就是读的更好.

*思考*是自我发现型学习与指导性学习的共性
"老师"的出席与缺席是这两种学习的主要区别
* 第二章 阅读的层次
一共分四层,之所以说是层而不是类.是因为这四层是循序渐进的.更高层的会包含低层次'
** 第一层---基础阅读
单纯指能识字,已经摆脱文盲的程度.能开始做阅读训练.
如果可以克服这个层次的困难,通常能让我们读的更快一些
** 第二层---检视阅读
略读或预读,在一定的时间内,抓住一本书的重点,检视阅读是系统化略读的一门艺术
在这个层次的目标是,从表面上观察这本书,学习到书的表面所教的一切
** 第三层次---分析阅读
花更多的时间的一种专注的活动,是咀嚼与消化一本书
** 第四层次---主题阅读
阅读大量的书,而不是一本书.是最主动的,也是最花费力气的一种阅读
* 第三章 阅读的第一个层次---基础阅读
  主要是在小学教育中训练
* 第四章 阅读的第二个层次---检视阅读
  检视阅读一共有两种,这是一体两面的事.
** 检视阅读一:有系统的略读或粗读
   略读的习惯不应花费过多的时间,我们重点关注:
   1. 书名和序
   2. 研究目录
   3. 检阅索引
   4. 阅读出版者的介绍
   5. 挑几个篇章看看(尤其是开头或结尾的摘要说明)
   6. 把书完整的翻一边,有时连续的读几页,但不要太多
** 检视阅读二:粗浅的阅读
   这时候的目标不在于弄懂书,而在于完整的把书读一遍(完整!!!).
   碰到不理解的先跳过,不停顿.这样才能有收获,而不是停在原地左顾右盼.
   对于后续的重复阅读也是有好处的.
* 第五章 如何做一个自我要求的作者
  阅读的目标如果是利益(不论什么方面的),就得保持清醒,要尽可能的保持主动.
** 主动阅读的核心:提出问题(这是绝不可忘的原则)
   可以尝试独自回答以下的问题(当然,不应该局限于这些问题.)
   1. 这本书的作者在讲述什么
   2. 作者着重在那些方面仔细的谈论过.
   3. 这本书书说的对吗?是完全对,还是部分对,或者是大错特错.(这个问题的答案建立在前两个问题的理解上)
   4. 这本书和自己有什么关系.我为什么要读这本书.(不应该用感兴趣来回答这个.)
** 如何让一本书真正属于你自己
   这个问题的答案是做笔记,这能保证自己清醒,
   还可以证明自己有在思考,另一方面可以记住作者的思想
   做笔记,其实就是在表达自己和作者相同或相异的观点,这是读者对作者最高的敬意.
** 三种做笔记的方法

*** 结构笔记
    重点在于全书的架构,而不是内容和细节,在检视阅读后应该可以完成.
*** 概念笔记
    重点在于记录作者的观点,以及自己的看法,这是在分析阅读的过程中慢慢补充的.
*** 辩证笔记
    在主题阅读中,就某一个主题,将多位作者和自己的观点比较,通常需要单独的来记录
** 培养阅读的习惯
   要养成习惯,除了不断的练习外,别无他法.
   艺术也是要按照规则,不断的练习的,一定的规则很重要.
   阅读的艺术也是如此.
** 由许多规则中养成一个习惯
   规则的多样化,表现出来的是养成习惯的复杂程度,而非要养成多个习惯
   熟悉规则,然后"忘记"规则,注意力也就能从这些习惯的规则转移到目标上了.
 
* 第六章 一本书的分类
** 书籍分类的重要性
   分析阅读的第一个规则就是:你一定要知道自己在读的是那一类的书,而且要愈早知道愈好,
   也就是说,应该在分析阅读前,也就是在检视阅读的阶段分辨出来.
** 从一本书的书名中你能学到什么?
   能一定的程度上帮助我们分辨出这本书的分类,但是很多时候并不能靠书名分辨出来
   重要的是形成自己的,对书籍分类的标准
** 实用性VS.理论性作品
*** 实用性:教会你做一些什么,同时也会有规劝的成分
    譬如说本书(如何阅读一本书),就是实用性的,在教我读书的同时,也在试图让我认同他的观点.

*** 理论性:试图让读者明白或了解某件事
    1. 历史就是纪事,历史学家在描述历史时,或多或少会带有自己的理解,评论或意见.
    2. 哲学与科学类似,他们都是追求一般真理,一般来说,讨论日常生活的
       是哲学类的,而超出了日常生活经验的则是科学.
* 第七章 透视一本书
  每一本书都有自己的一套框架,分析阅读的目标之一就是理清楚这一套框架.
  由此引出分析阅读的第二个规则:尝试用尽可能短的文字,语句,来描述一本书的内容.
  PS.如果你的描述使用的文字过多,只能说明你并没有将整体的内容看清楚,而只是看到了多样的内容.
  而分析阅读的第三个规则是:将书中重要的章节列举出来,说明他们如何按照顺序组成一个整体.
  在这里重要的是,理清楚他们是如何组成的一个整体,而不是简单的把他们列举出来.
** 结构与规划
   一本书的结构与规划,能叙述整本书的大意.
** 驾驭复杂的内容:为一本书拟大纲的技巧
   第二个规则与第三个规则联系紧密,但是合在一起则是复杂的规则,
   将复杂的事情拆开有助于解决问题.
   不用为所有书写纲要,有些书不值得,你也没有那么多的时间.
   但是读完一本书,至少心中要对这本书有一个模糊的大纲.
   大纲也不一定要十分的完美,对重要的好书,尽可能的按照规则来写即可.
   不一定要按照原书出现的章节来归纳一本书的架构,你有可能做的更好.
   原书的章节是指南,是可以参考的.但是不能依赖它.
   只有做好第三个规则,才能做好第二个规则.
   实际上这两个(第二和第三)规则,除了可以对一整本书使用,也可以对书中某一个章节使用.
** 发现作者的意图
   分析阅读的第四个规则:找出作者要问的问题.
   第四个规则和前两个规则有着前后呼应的效果.
** 分析阅读的第一个阶段
   第一个阶段就是完成以上的四个分析阅读的规则.
   但是要记住,并不是说详细的读完一遍整本书,只完成这第一个阶段.
   而是说:多个阶段同时进行,读者应该多思考,而不是局限于某一个方面去思考.
* 第八章 与作者找出共通的词义
  在自然语言中,字词或多或少的会出现歧义,
  这里的目标就是正确的理解作者想要传达给读者的东西.
  如果这点做不到，那么阅读就没有收获。
  在这个过程中,读者需要自己努力的思考.
  分析阅读第五个规则：找出重要的单字，透过他们与作者达成共识。
** 找出关键字
   这是作者希望你能注意到的字词
   从一个读者的角度来看，最重要的字也就是那些让读者头疼的字。
** 专门用语以及特殊字汇
   每一个知识领域都有独特的专门用语。
   译者这里的专门用语在或许用专有名词更好？
   读者应该有好奇心去了解那些专门用语和特殊字汇到底代表着什么，
   否则，读者和作者之间的沟通就不存在了
** 找出词义
   一定要用上下文自己已经了解的所有字句，来推敲出你所不了解的那些字词的意义
   文字和词义是本章最重要的两个东西，
   文字：是作者之间写出来的，读者直接能够观察到的。
   词义：某一段文字中，作者想要传递给读者的信息。
   自然语言都是模糊不清的。
   同一短文字可以有很多不同的词义，另一方面，不同的文字有可能代表同样的词义。
   实际上，书中的文字一般是不中要的（专业的术语很重要，比如数学的极限）读者真正需要的是找出词义
* 判断作者的主旨
